Error: nlopt refuses to finish (returns -1)
Also, I changed second_order_model because I was getting an F_X not
defined error, which is nonsensical. Added verbose mode, continuing
testing.